    !######################################################################!
    !#                                                                    #!
    !#                              步骤子函数                            #!
    !#                                                                    #!
    !######################################################################!

    !******************************************初始化*****************************************************!
    SUBROUTINE ALLOCATION_VARIABLE_FILE
    USE DECLARATION
    USE IMMERSED_BOUNDARY
    USE QUADRIC_PARAMETER
    IMPLICIT NONE

    ALLOCATE( X(IM),Y(JM) )
    ALLOCATE( XPV(0:IM),YPU(0:JM) )
    ALLOCATE( U(IM,0:JM),V(0:IM,JM),P(IM-1,JM-1),PHI(0:IM,0:JM) )
    ALLOCATE( UN(IM,0:JM),VN(0:IM,JM) )
    ALLOCATE( UM(IM,0:JM),VM(0:IM,JM),UM1(IM,0:JM),VM1(0:IM,JM),UM2(IM,0:JM),VM2(0:IM,JM) )!R-K格式
    !ALLOCATE( UN1(IM,0:JM),VN1(0:IM,JM) )!A-B格式
    ALLOCATE( UHAT(IM,0:JM),VHAT(0:IM,JM) )

    ALLOCATE( TYPEUX(IM,0:JM),TYPEVX(0:IM,JM) )
    ALLOCATE( IB_RUX(IM,0:JM),IB_RVX(0:IM,JM) )
    ALLOCATE( IB_AUX(IM,0:JM),IB_AVX(0:IM,JM) )
    ALLOCATE( IB_CUX(IM,0:JM),IB_CVX(0:IM,JM) )
    ALLOCATE( TYPEUY(IM,0:JM),TYPEVY(0:IM,JM) )
    ALLOCATE( IB_RUY(IM,0:JM),IB_RVY(0:IM,JM) )
    ALLOCATE( IB_BUY(IM,0:JM),IB_BVY(0:IM,JM) )
    ALLOCATE( IB_CUY(IM,0:JM),IB_CVY(0:IM,JM) )

    ALLOCATE( LAPLACE_UXM1(IM,0:JM),LAPLACE_VXM1(0:IM,JM) )
    ALLOCATE( LAPLACE_UYM1(IM,0:JM),LAPLACE_VYM1(0:IM,JM) )
    ALLOCATE( CONVECT_UXM1(IM,0:JM),CONVECT_VXM1(0:IM,JM) )
    ALLOCATE( CONVECT_UYM1(IM,0:JM),CONVECT_VYM1(0:IM,JM) )
    ALLOCATE( CONVECT_UXM2(IM,0:JM),CONVECT_VXM2(0:IM,JM) )
    ALLOCATE( CONVECT_UYM2(IM,0:JM),CONVECT_VYM2(0:IM,JM) )

    LAPLACE_UXM1=TRANSFER((/ Z'00000000', Z'7FF80000' /),1.0_8)
    LAPLACE_VXM1=TRANSFER((/ Z'00000000', Z'7FF80000' /),1.0_8)
    LAPLACE_UYM1=TRANSFER((/ Z'00000000', Z'7FF80000' /),1.0_8)
    LAPLACE_VYM1=TRANSFER((/ Z'00000000', Z'7FF80000' /),1.0_8)
    CONVECT_UXM1=TRANSFER((/ Z'00000000', Z'7FF80000' /),1.0_8)
    CONVECT_VXM1=TRANSFER((/ Z'00000000', Z'7FF80000' /),1.0_8)
    CONVECT_UYM1=TRANSFER((/ Z'00000000', Z'7FF80000' /),1.0_8)
    CONVECT_VYM1=TRANSFER((/ Z'00000000', Z'7FF80000' /),1.0_8)
    CONVECT_UXM2=0.0D0
    CONVECT_VXM2=0.0D0
    CONVECT_UYM2=0.0D0
    CONVECT_VYM2=0.0D0

    ALLOCATE( TYPEUXM1(IM,0:JM),TYPEVXM1(0:IM,JM) )
    ALLOCATE( TYPEUYM1(IM,0:JM),TYPEVYM1(0:IM,JM) )

    ALLOCATE( IB_ITSCT_UX(IM,0:JM),IB_ITSCT_VX(0:IM,JM) )
    ALLOCATE( IB_IPSVL_UX(IM,0:JM),IB_IPSVL_VX(0:IM,JM) )
    ALLOCATE( IB_ITSCT_UY(IM,0:JM),IB_ITSCT_VY(0:IM,JM) )
    ALLOCATE( IB_IPSVL_UY(IM,0:JM),IB_IPSVL_VY(0:IM,JM) )
    ALLOCATE( IB_IPSVL_UXV(IM,0:JM),IB_IPSVL_VXU(0:IM,JM) )
    ALLOCATE( IB_IPSVL_UYV(IM,0:JM),IB_IPSVL_VYU(0:IM,JM) )

    ALLOCATE( IB_ITSCT_UXN(IM,0:JM),IB_ITSCT_VXN(0:IM,JM) )
    ALLOCATE( IB_IPSVL_UXN(IM,0:JM),IB_IPSVL_VXN(0:IM,JM) )
    ALLOCATE( IB_ITSCT_UYN(IM,0:JM),IB_ITSCT_VYN(0:IM,JM) )
    ALLOCATE( IB_IPSVL_UYN(IM,0:JM),IB_IPSVL_VYN(0:IM,JM) )
    ALLOCATE( IB_IPSVL_UXVN(IM,0:JM),IB_IPSVL_VXUN(0:IM,JM) )
    ALLOCATE( IB_IPSVL_UYVN(IM,0:JM),IB_IPSVL_VYUN(0:IM,JM) )

    ALLOCATE( IBN1_IPSVL_UXN(IM,0:JM),IBN1_IPSVL_VXN(0:IM,JM) )
    ALLOCATE( IBN1_IPSVL_UYN(IM,0:JM),IBN1_IPSVL_VYN(0:IM,JM) )

    !OPEN(UNIT=20,FILE='升阻力系数.DAT')
    OPEN(UNIT=30,FILE='残差.DAT')
    OPEN(UNIT=40,FILE='位置.DAT')
    !OPEN(UNIT=50,FILE='时间.DAT')

    OPEN(UNIT=60,FILE='探针1.DAT')
    OPEN(UNIT=70,FILE='探针2.DAT')
    OPEN(UNIT=80,FILE='探针3.DAT')
    OPEN(UNIT=90,FILE='探针4.DAT')
    !~!
    !OPEN(UNIT=100,FILE='虚拟时间步残差.DAT')

    OPEN(UNIT=180,FILE='角度1.DAT')
    OPEN(UNIT=190,FILE='速度1.DAT')
    OPEN(UNIT=200,FILE='角度2.DAT')
    OPEN(UNIT=210,FILE='速度2.DAT')
    OPEN(UNIT=220,FILE='质心1.DAT')
    OPEN(UNIT=230,FILE='质心2.DAT')

    IF(BOUNDARY_EXISTENCE_1==1)THEN
        OPEN(UNIT=300,FILE='CXC_CYC_CXT_CYT_CXF_CYF_1.DAT')
        OPEN(UNIT=301,FILE='CU_CP_CUX_CUY_CPX_CPY_1.DAT')
        OPEN(UNIT=302,FILE='CP_PROP_ELEV_EFFE_AERO_1.DAT')
        OPEN(UNIT=303,FILE='E_PROP_ELEV_TOTAL_1.DAT')
    END IF
    IF(BOUNDARY_EXISTENCE_2==1)THEN
        OPEN(UNIT=305,FILE='CXC_CYC_CXT_CYT_CXF_CYF_2.DAT')
        OPEN(UNIT=306,FILE='CU_CP_CUX_CUY_CPX_CPY_2.DAT')
        OPEN(UNIT=307,FILE='CP_PROP_ELEV_EFFE_AERO_2.DAT')
        OPEN(UNIT=308,FILE='E_PROP_ELEV_TOTAL_2.DAT')
    END IF
    !OPEN(UNIT=300,FILE='FOREWING_CLCTE_TOTAL.DAT')
    !OPEN(UNIT=310,FILE='FOREWING_CXS.CSV')
    !OPEN(UNIT=320,FILE='FOREWING_CYS.CSV')
    !OPEN(UNIT=330,FILE='FOREWING_CP_PROP.CSV')
    !OPEN(UNIT=340,FILE='FOREWING_CP_ELEV.CSV')
    !OPEN(UNIT=350,FILE='FOREWING_CP_EFFE.CSV')
    !OPEN(UNIT=360,FILE='FOREWING_CP_AERO.CSV')
    !OPEN(UNIT=370,FILE='FOREWING_EFFICIENCY.CSV')
    !
    !OPEN(UNIT=400,FILE='HINDWING_CLCTE_TOTAL.DAT')
    !OPEN(UNIT=410,FILE='HINDWING_CXS.CSV')
    !OPEN(UNIT=420,FILE='HINDWING_CYS.CSV')
    !OPEN(UNIT=430,FILE='HINDWING_CP_PROP.CSV')
    !OPEN(UNIT=440,FILE='HINDWING_CP_ELEV.CSV')
    !OPEN(UNIT=450,FILE='HINDWING_CP_EFFE.CSV')
    !OPEN(UNIT=460,FILE='HINDWING_CP_AERO.CSV')
    !OPEN(UNIT=470,FILE='HINDWING_EFFICIENCY.CSV')
    !
    !OPEN(UNIT=990,FILE='PPHIDELTAU1.DAT')
    !OPEN(UNIT=991,FILE='PPHIDELTAU2.DAT')
    OPEN(UNIT=992,FILE='IBN1_IPSVL_VYN_ERROR.DAT')
    
    !后处理模块
    OPEN(UNIT=500,FILE='压力分布数值.DAT')
    OPEN(UNIT=501,FILE='压力分布角度.DAT')
    
    RETURN
    END SUBROUTINE