    !######################################################################!
    !#                                                                    #!
    !#                              ≤Ω÷Ë◊”∫Ø ˝                            #!
    !#                                                                    #!
    !######################################################################!

    !*************************************«ÛΩ‚ ˝÷µÃΩ’ÎŒª÷√–≈œ¢******************************************!
    SUBROUTINE CAL_PROBE
    USE DECLARATION
    IMPLICIT NONE
    
    REAL(KIND=8),ALLOCATABLE::PROBEX(:),PROBEY(:)
    INTEGER::PORBE_LOC
    
    ALLOCATE( PROBEX(IM),PROBEY(JM) )
    
    !ÃΩ’Î1
    PROBEX=XPV(:)-PROBE_X1
    PROBEY=YPU(:)-PROBE_Y1
    PROBE_IPV1=MINLOC( DABS(PROBEX),1 )
    PROBE_JPU1=MINLOC( DABS(PROBEY),1 )
    IF( XPV(PROBE_IPV1)>PROBE_X1 ) PROBE_IPV1=PROBE_IPV1-1
    IF( YPU(PROBE_JPU1)>PROBE_Y1 ) PROBE_JPU1=PROBE_JPU1-1
    PROBEX=X(:)-PROBE_X1
    PROBE_IU1=MINLOC( DABS(PROBEX),1 )
    IF( X(PROBE_IU1)>PROBE_X1 ) PROBE_IU1=PROBE_IU1-1
    PROBEY=Y(:)-PROBE_Y1
    PROBE_JV1=MINLOC( DABS(PROBEY),1 )
    IF( Y(PROBE_JV1)>PROBE_Y1 ) PROBE_JV1=PROBE_JV1-1
    !ÃΩ’Î2
    PROBEX=XPV(:)-PROBE_X2
    PROBEY=YPU(:)-PROBE_Y2
    PROBE_IPV2=MINLOC( DABS(PROBEX),1 )
    PROBE_JPU2=MINLOC( DABS(PROBEY),1 )
    IF( XPV(PROBE_IPV2)>PROBE_X2 ) PROBE_IPV2=PROBE_IPV2-1
    IF( YPU(PROBE_JPU2)>PROBE_Y2 ) PROBE_JPU2=PROBE_JPU2-1
    PROBEX=X(:)-PROBE_X2
    PROBE_IU2=MINLOC( DABS(PROBEX),1 )
    IF( X(PROBE_IU2)>PROBE_X2 ) PROBE_IU2=PROBE_IU2-1
    PROBEY=Y(:)-PROBE_Y2
    PROBE_JV2=MINLOC( DABS(PROBEY),1 )
    IF( Y(PROBE_JV2)>PROBE_Y2 ) PROBE_JV2=PROBE_JV2-1
    !ÃΩ’Î3
    PROBEX=XPV(:)-PROBE_X3
    PROBEY=YPU(:)-PROBE_Y3
    PROBE_IPV3=MINLOC( DABS(PROBEX),1 )
    PROBE_JPU3=MINLOC( DABS(PROBEY),1 )
    IF( XPV(PROBE_IPV3)>PROBE_X3 ) PROBE_IPV3=PROBE_IPV3-1
    IF( YPU(PROBE_JPU3)>PROBE_Y3 ) PROBE_JPU3=PROBE_JPU3-1
    PROBEX=X(:)-PROBE_X3
    PROBE_IU3=MINLOC( DABS(PROBEX),1 )
    IF( X(PROBE_IU3)>PROBE_X3 ) PROBE_IU3=PROBE_IU3-1
    PROBEY=Y(:)-PROBE_Y3
    PROBE_JV3=MINLOC( DABS(PROBEY),1 )
    IF( Y(PROBE_JV3)>PROBE_Y3 ) PROBE_JV3=PROBE_JV3-1
    !ÃΩ’Î4
    PROBEX=XPV(:)-PROBE_X4
    PROBEY=YPU(:)-PROBE_Y4
    PROBE_IPV4=MINLOC( DABS(PROBEX),1 )
    PROBE_JPU4=MINLOC( DABS(PROBEY),1 )
    IF( XPV(PROBE_IPV4)>PROBE_X4 ) PROBE_IPV4=PROBE_IPV4-1
    IF( YPU(PROBE_JPU4)>PROBE_Y4 ) PROBE_JPU4=PROBE_JPU4-1
    PROBEX=X(:)-PROBE_X4
    PROBE_IU4=MINLOC( DABS(PROBEX),1 )
    IF( X(PROBE_IU4)>PROBE_X4 ) PROBE_IU4=PROBE_IU4-1
    PROBEY=Y(:)-PROBE_Y4
    PROBE_JV4=MINLOC( DABS(PROBEY),1 )
    IF( Y(PROBE_JV4)>PROBE_Y4 ) PROBE_JV4=PROBE_JV4-1
    
    OPEN(UNIT=10,FILE='ÃΩ’Î–≈œ¢.DAT')
    WRITE(10,*) 'ÃΩ’Î1'
    WRITE(10,*) PROBE_IPV1,PROBE_JPU1,PROBE_IU1,PROBE_JV1
    WRITE(10,*) XPV(PROBE_IPV1),YPU(PROBE_JPU1),X(PROBE_IU1),Y(PROBE_JV1)
    WRITE(10,*) 'ÃΩ’Î2'
    WRITE(10,*) PROBE_IPV2,PROBE_JPU2,PROBE_IU2,PROBE_JV2
    WRITE(10,*) XPV(PROBE_IPV2),YPU(PROBE_JPU2),X(PROBE_IU2),Y(PROBE_JV2)
    WRITE(10,*) 'ÃΩ’Î3'
    WRITE(10,*) PROBE_IPV3,PROBE_JPU3,PROBE_IU3,PROBE_JV3
    WRITE(10,*) XPV(PROBE_IPV3),YPU(PROBE_JPU3),X(PROBE_IU3),Y(PROBE_JV3)
    WRITE(10,*) 'ÃΩ’Î4'
    WRITE(10,*) PROBE_IPV4,PROBE_JPU4,PROBE_IU4,PROBE_JV4
    WRITE(10,*) XPV(PROBE_IPV4),YPU(PROBE_JPU4),X(PROBE_IU4),Y(PROBE_JV4)
    CLOSE(10)
    
    
    RETURN
    END SUBROUTINE