    !######################################################################!
    !#                                                                    #!
    !#                              步骤子函数                            #!
    !#                                                                    #!
    !######################################################################!

    !*************************************输出速度分布******************************************!
    SUBROUTINE OUTPUT_VELOCITY_PROFILE
    USE DECLARATION
    IMPLICIT NONE
    CHARACTER(LEN=80)::FILENAME="2DXYRe00100N005500-330.PLT"
    REAL(KIND=8)::VALUE_X1,VALUE_Y1
    REAL(KIND=8)::VALUE_X2,VALUE_Y2
    REAL(KIND=8)::VALUE_X3,VALUE_Y3
    REAL(KIND=8)::VALUE_X4,VALUE_Y4
    REAL(KIND=8)::RANGE1,RANGE2!RANGE1<RANGE2
    INTEGER::VALUE_IU1,VALUE_JV1
    INTEGER::VALUE_IPV1,VALUE_JPU1
    INTEGER::VALUE_IU2,VALUE_JV2
    INTEGER::VALUE_IPV2,VALUE_JPU2
    INTEGER::VALUE_IU3,VALUE_JV3
    INTEGER::VALUE_IPV3,VALUE_JPU3
    INTEGER::VALUE_IU4,VALUE_JV4
    INTEGER::VALUE_IPV4,VALUE_JPU4
    REAL(KIND=8),ALLOCATABLE::PROBEX(:),PROBEY(:)
    REAL(KIND=8),ALLOCATABLE::PROBEXPV(:),PROBEYPU(:)
    REAL(KIND=8),ALLOCATABLE::U_OUT(:),V_OUT(:)

    ALLOCATE( PROBEX(IM),PROBEY(JM) )
    ALLOCATE( PROBEXPV(0:IM),PROBEYPU(0:JM) )

    !------输出Y方向的速度型------!
    !VALUE_Y1= 0.6D0
    !VALUE_Y2= 0.0D0
    !VALUE_Y3=-0.6D0
    !VALUE_Y4=-1.2D0
    !
    !RANGE1=-1.1D0
    !RANGE2= 1.1D0
    !
    !!PROBEX=X(:)-VALUE_X1
    !!VALUE_I1=MINLOC( DABS(PROBEX),1 )
    !!IF( X(VALUE_I1)>VALUE_X1 ) VALUE_I1=VALUE_I1-1
    !
    !!PROBEY=YPU(:)-VALUE_Y1
    !!VALUE_J1=MINLOC( DABS(PROBEY),1 )
    !!IF( YPU(VALUE_J1)>VALUE_Y1 ) VALUE_J1=VALUE_J1-1
    !!
    !!PROBEY=YPU(:)-VALUE_Y2
    !!VALUE_J2=MINLOC( DABS(PROBEY),1 )
    !!IF( YPU(VALUE_J2)>VALUE_Y2 ) VALUE_J2=VALUE_J2-1
    !!
    !!PROBEY=YPU(:)-VALUE_Y3
    !!VALUE_J3=MINLOC( DABS(PROBEY),1 )
    !!IF( YPU(VALUE_J3)>VALUE_Y3 ) VALUE_J3=VALUE_J3-1
    !!
    !!PROBEY=YPU(:)-VALUE_Y4
    !!VALUE_J4=MINLOC( DABS(PROBEY),1 )
    !!IF( YPU(VALUE_J4)>VALUE_Y4 ) VALUE_J4=VALUE_J4-1
    !
    !PROBEYPU=YPU(:)-VALUE_Y1
    !VALUE_JPU1=MINLOC( DABS(PROBEYPU),1 )
    !IF( YPU(VALUE_JPU1)>VALUE_Y1 ) VALUE_JPU1=VALUE_JPU1-1
    !
    !PROBEYPU=YPU(:)-VALUE_Y2
    !VALUE_JPU2=MINLOC( DABS(PROBEYPU),1 )
    !IF( YPU(VALUE_JPU2)>VALUE_Y2 ) VALUE_JPU2=VALUE_JPU2-1
    !
    !PROBEYPU=YPU(:)-VALUE_Y3
    !VALUE_JPU3=MINLOC( DABS(PROBEYPU),1 )
    !IF( YPU(VALUE_JPU3)>VALUE_Y3 ) VALUE_JPU3=VALUE_JPU3-1
    !
    !PROBEYPU=YPU(:)-VALUE_Y4
    !VALUE_JPU4=MINLOC( DABS(PROBEYPU),1 )
    !IF( YPU(VALUE_JPU4)>VALUE_Y4 ) VALUE_JPU4=VALUE_JPU4-1
    !
    !PROBEX=X(:)-RANGE1
    !VALUE_IU1=MINLOC( DABS(PROBEX),1 )
    !IF( X(VALUE_IU1)>RANGE1 ) VALUE_IU1=VALUE_IU1-1
    !
    !PROBEX=X(:)-RANGE2
    !VALUE_IU2=MINLOC( DABS(PROBEX),1 )
    !IF( X(VALUE_IU2)<RANGE2 ) VALUE_IU2=VALUE_IU2+1
    !
    !CALL READFROMFILE_2D_STAGGERED(FILENAME)
    !
    !ALLOCATE( U_OUT(IM),V_OUT(IM) )
    !
    !OPEN(UNIT=10,FILE='速度分布06.DAT')
    !DO I=VALUE_IU1,VALUE_IU2,1
    !    CALL LINEAR_INTERPOLATION( U(I,VALUE_JPU1+1),U_OUT(I),U(I,VALUE_JPU1),YPU(VALUE_JPU1+1),VALUE_Y1,YPU(VALUE_JPU1) )
    !    WRITE(10,*) X(I),VALUE_Y1,U_OUT(I)
    !END DO
    !CLOSE(10)
    !
    !OPEN(UNIT=10,FILE='速度分布00.DAT')
    !DO I=VALUE_IU1,VALUE_IU2,1
    !    CALL LINEAR_INTERPOLATION( U(I,VALUE_JPU2+1),U_OUT(I),U(I,VALUE_JPU2),YPU(VALUE_JPU2+1),VALUE_Y2,YPU(VALUE_JPU2) )
    !    WRITE(10,*) X(I),VALUE_Y2,U_OUT(I)
    !END DO
    !CLOSE(10)
    !
    !OPEN(UNIT=10,FILE='速度分布-06.DAT')
    !DO I=VALUE_IU1,VALUE_IU2,1
    !    CALL LINEAR_INTERPOLATION( U(I,VALUE_JPU3+1),U_OUT(I),U(I,VALUE_JPU3),YPU(VALUE_JPU3+1),VALUE_Y3,YPU(VALUE_JPU3) )
    !    WRITE(10,*) X(I),VALUE_Y3,U_OUT(I)
    !END DO
    !CLOSE(10)
    !
    !OPEN(UNIT=10,FILE='速度分布-12.DAT')
    !DO I=VALUE_IU1,VALUE_IU2,1
    !    CALL LINEAR_INTERPOLATION( U(I,VALUE_JPU4+1),U_OUT(I),U(I,VALUE_JPU4),YPU(VALUE_JPU4+1),VALUE_Y4,YPU(VALUE_JPU4) )
    !    WRITE(10,*) X(I),VALUE_Y4,U_OUT(I)
    !END DO
    !CLOSE(10)

    !------输出X方向的速度型------!
    VALUE_X1=-0.6D0
    VALUE_X2= 0.0D0
    VALUE_X3= 0.6D0
    VALUE_X4= 1.2D0

    RANGE1=-1.1D0
    RANGE2= 1.1D0

    PROBEX=X(:)-VALUE_X1
    VALUE_IU1=MINLOC( DABS(PROBEX),1 )
    IF( X(VALUE_IU1)>VALUE_X1 ) VALUE_IU1=VALUE_IU1-1

    PROBEX=X(:)-VALUE_X2
    VALUE_IU2=MINLOC( DABS(PROBEX),1 )
    IF( X(VALUE_IU2)>VALUE_X2 ) VALUE_IU2=VALUE_IU2-1

    PROBEX=X(:)-VALUE_X3
    VALUE_IU3=MINLOC( DABS(PROBEX),1 )
    IF( X(VALUE_IU3)>VALUE_X3 ) VALUE_IU3=VALUE_IU3-1

    PROBEX=X(:)-VALUE_X4
    VALUE_IU4=MINLOC( DABS(PROBEX),1 )
    IF( X(VALUE_IU4)>VALUE_X4 ) VALUE_IU4=VALUE_IU4-1

    PROBEYPU=YPU(:)-RANGE1
    VALUE_JPU1=MINLOC( DABS(PROBEYPU),1 )
    IF( YPU(VALUE_JPU1)>RANGE1 ) VALUE_JPU1=VALUE_JPU1-1

    PROBEYPU=YPU(:)-RANGE2
    VALUE_JPU2=MINLOC( DABS(PROBEYPU),1 )
    IF( YPU(VALUE_JPU2)>RANGE2 ) VALUE_JPU2=VALUE_JPU2-1

    CALL READFROMFILE_2D_STAGGERED(FILENAME)

    ALLOCATE( U_OUT(JM),V_OUT(JM) )

    OPEN(UNIT=10,FILE='速度分布X-06.DAT')
    DO J=VALUE_JPU1,VALUE_JPU2,1
        CALL LINEAR_INTERPOLATION( U(VALUE_IU1+1,J),U_OUT(J),U(VALUE_IU1,J),X(VALUE_IU1+1),VALUE_X1,X(VALUE_IU1) )
        WRITE(10,*) YPU(J),VALUE_X1,U_OUT(J)
    END DO
    CLOSE(10)

    OPEN(UNIT=10,FILE='速度分布X00.DAT')
    DO J=VALUE_JPU1,VALUE_JPU2,1
        CALL LINEAR_INTERPOLATION( U(VALUE_IU2+1,J),U_OUT(J),U(VALUE_IU2,J),X(VALUE_IU2+1),VALUE_X2,X(VALUE_IU2) )
        WRITE(10,*) YPU(J),VALUE_X2,U_OUT(J)
    END DO
    CLOSE(10)

    OPEN(UNIT=10,FILE='速度分布X06.DAT')
    DO J=VALUE_JPU1,VALUE_JPU2,1
        CALL LINEAR_INTERPOLATION( U(VALUE_IU3+1,J),U_OUT(J),U(VALUE_IU3,J),X(VALUE_IU3+1),VALUE_X3,X(VALUE_IU3) )
        WRITE(10,*) YPU(J),VALUE_X3,U_OUT(J)
    END DO
    CLOSE(10)

    OPEN(UNIT=10,FILE='速度分布X12.DAT')
    DO J=VALUE_JPU1,VALUE_JPU2,1
        CALL LINEAR_INTERPOLATION( U(VALUE_IU4+1,J),U_OUT(J),U(VALUE_IU4,J),X(VALUE_IU4+1),VALUE_X4,X(VALUE_IU4) )
        WRITE(10,*) YPU(J),VALUE_X4,U_OUT(J)
    END DO
    CLOSE(10)

    !------输出X方向的速度型DRIVENCAVITY------!
    !VALUE_X1= 0.5D0
    !
    !RANGE1=-0.0D0
    !RANGE2= 1.0D0
    !
    !PROBEX=X(:)-VALUE_X1
    !VALUE_IU1=MINLOC( DABS(PROBEX),1 )
    !IF( X(VALUE_IU1)>VALUE_X1 ) VALUE_IU1=VALUE_IU1-1
    !
    !PROBEYPU=YPU(:)-RANGE1
    !VALUE_JPU1=MINLOC( DABS(PROBEYPU),1 )
    !IF( YPU(VALUE_JPU1)>RANGE1 ) VALUE_JPU1=VALUE_JPU1-1
    !
    !PROBEYPU=YPU(:)-RANGE2
    !VALUE_JPU2=MINLOC( DABS(PROBEYPU),1 )
    !IF( YPU(VALUE_JPU2)>RANGE2 ) VALUE_JPU2=VALUE_JPU2-1
    !
    !CALL READFROMFILE_2D_STAGGERED(FILENAME)
    !
    !ALLOCATE( U_OUT(JM),V_OUT(JM) )
    !
    !OPEN(UNIT=10,FILE='速度分布X05.DAT')
    !DO J=VALUE_JPU1,VALUE_JPU2,1
    !    CALL LINEAR_INTERPOLATION( U(VALUE_IU1+1,J),U_OUT(J),U(VALUE_IU1,J),X(VALUE_IU1+1),VALUE_X1,X(VALUE_IU1) )
    !    WRITE(10,*) YPU(J),VALUE_X1,U_OUT(J)
    !END DO
    !CLOSE(10)



    RETURN
    END SUBROUTINE